replicaCount: 2
resources:
  limits:
    memory: "128Mi"
    cpu: "500m"

hpa:
  enabled: false
  minReplicas: 2
  maxReplicas: 10
  cpuUtilization: 80

env:
  direct:
    - name: ASPNETCORE_ENVIRONMENT
      value: Development
  fromSecret:
    enabled: false
    secretName: asp-template-secret
    envVars:
      - name: API_KEY
        key: apiKey
      - name: DATABASE_URL
        key: databaseUrl

image:
  repository: ndknitor/asp-template
  tag: "latest"
  pullPolicy: IfNotPresent
  pullSecret: ""

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  annotations:
    #  nginx.ingress.kubernetes.io/affinity: "true" # Enable session affinity
    #  nginx.ingress.kubernetes.io/affinity-mode: "ip" # IP-based session affinity
    #  nginx.ingress.kubernetes.io/affinity-type: "ip" # Use client IP for session affinity
    #  nginx.ingress.kubernetes.io/affinity-avg-latency-type: "wlc" # Use least connection method

    # nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    # nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    # nginx.ingress.kubernetes.io/server-snippets: |
    #   location / {
    #     proxy_set_header Upgrade $http_upgrade;
    #     proxy_http_version 1.1;
    #     proxy_set_header X-Forwarded-Host $http_host;
    #     proxy_set_header X-Forwarded-Proto $scheme;
    #     proxy_set_header X-Forwarded-For $remote_addr;
    #     proxy_set_header Host $host;
    #     proxy_set_header Connection "upgrade";
    #     proxy_cache_bypass $http_upgrade;
    #   }
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: asp-template.com
      paths:
        - path: /
          pathType: Prefix
  # tls:
  #   - secretName: asp-template-tls-secret
  #     hosts:
  #       - asp-template.com
